source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '6.1.4.4'
gem 'pg', '1.2.3'
gem 'puma', '4.3.12'
gem 'bootsnap', '1.10.1', require: false
gem 'rack-cors', '1.1.1'

group :development do
  gem 'spring'
  gem 'spring-watcher-listen', '2.0.1'
end

group :development, :test do
  gem 'listen', '3.7.1'
  gem 'factory_bot_rails'
  gem 'rubocop', '~> 0.79.0', require: false
  gem 'rubocop-rails', require: false
  gem 'rspec-rails'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'pry-rails'
  gem 'database_cleaner'
end
